// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5MP1N2N9vWEG2zEM4LMTWT4VNPGaT1WA',
    appId: '1:802519577304:web:d8c1291dec6b728753ddad',
    messagingSenderId: '802519577304',
    projectId: 'emaillogin-ae7d2',
    authDomain: 'emaillogin-ae7d2.firebaseapp.com',
    storageBucket: 'emaillogin-ae7d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeeWnQp6ezIEFYB1LzDGZYgFrhf4nHq1U',
    appId: '1:802519577304:android:5fe3f616763d9cab53ddad',
    messagingSenderId: '802519577304',
    projectId: 'emaillogin-ae7d2',
    storageBucket: 'emaillogin-ae7d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxdbG28GcqXyuRqGCg97Nx4OSA0CsDcYo',
    appId: '1:802519577304:ios:5e0d537842dad08653ddad',
    messagingSenderId: '802519577304',
    projectId: 'emaillogin-ae7d2',
    storageBucket: 'emaillogin-ae7d2.appspot.com',
    iosClientId: '802519577304-qi1mg67too14f1vhot7kispdf1hmd1q9.apps.googleusercontent.com',
    iosBundleId: 'com.example.model2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxdbG28GcqXyuRqGCg97Nx4OSA0CsDcYo',
    appId: '1:802519577304:ios:ffe790fa72dd9bd353ddad',
    messagingSenderId: '802519577304',
    projectId: 'emaillogin-ae7d2',
    storageBucket: 'emaillogin-ae7d2.appspot.com',
    iosClientId: '802519577304-o012oli99869rq3tmc3tasql4ao1gpet.apps.googleusercontent.com',
    iosBundleId: 'com.example.model2.RunnerTests',
  );
}
